export type SectionDefinition = {
  folder: string;
  title: string;
  subtitle: string;
  description: string;
  chapterLabel: string;
};

export const galleryCopy = {
  hero: {
    title: "The Family",
    message: "Happy Birthday, Mama & Baba",
    description:
      "A journey through our most precious memories, from the beginning to whatever comes next.",
    babaLabel: "Baba",
    mamaLabel: "Mama",
    scrollLabel: "Scroll",
  },
  divider: {
    title: "Highlighted Moments",
    subtitle: "The photos that tell their own stories",
  },
  closing: {
    eyebrow: "Always & forever",
    title: "The Story Continues",
    description:
      "The best is yet to come. Some more moments since then, graduating, going to college, and whatever comes next.",
    quote:
      '"Family is not an important thing.\nIt\'s everything."',
    quoteAuthor: "Michael J. Fox",
  },
  finalNote: {
    eyebrow: "Concluding Section",
    title: "A Final Note",
    description:
      "Happy Birthday Mama and Baba! Thank you so much for supporting me through every step of my life and giving me everything I could hope for. I am so grateful for everything you do for me, my nonsense you put up with, and for guiding me in countless ways. I miss and love you both and I can't wait to be back all together in Australia.",
    imageSrc: "/last-image.png",
    imageAlt: "Final family photo",
  },
} as const;

export const sectionDefinitions: SectionDefinition[] = [
  { folder: "2006", title: "2006", subtitle: "The Beginning", chapterLabel: "Growing Up", description: "The year I was born! The very beginning of our family, way back in Bismarck, North Dakota." },
  { folder: "2007", title: "2007", subtitle: "The Start of Travel Together", chapterLabel: "Growing Up", description: "The year we started traveling together as a family. Lego land, Pakistan, and more!" },
  { folder: "2008", title: "2008", subtitle: "The Beach", chapterLabel: "Growing Up", description: "Traveled even more, hit Atlantis, learned to swim, explored the beach, and rode a horse!" },
  { folder: "2009", title: "2009", subtitle: "Through Every Season", chapterLabel: "Growing Up", description: "Growing up together, first Halloween, and more adventures!" },
  { folder: "2010", title: "2010", subtitle: "In Full Bloom", chapterLabel: "Growing Up", description: "A move to St.Louis, same family seeing new places!" },
  { folder: "2011", title: "2011", subtitle: "Side by Side", chapterLabel: "Growing Up", description: "More trips, birthdays, and adventures!" },
  { folder: "2012", title: "2012", subtitle: "The Shazi Era", chapterLabel: "Growing Up", description: "Shazi is born! Family of 4 now with Shazi's amazing tantrums." },
  { folder: "2013", title: "2013", subtitle: "New Horizons", chapterLabel: "Growing Up", description: "Shazi joins us on the trips as we see more beaches, cities, and have more adventures together." },
  { folder: "Greece:Turkey", title: "Greece & Turkey", subtitle: "Ancient Wonders", chapterLabel: "Adventures", description: "Where East meets West, and Shazi's first major trip with us all together." },
  { folder: "Caymen Islands", title: "Cayman Islands", subtitle: "Island Paradise", chapterLabel: "Adventures", description: "Crystal waters and Stingray city!!" },
  { folder: "Italy", title: "Italy", subtitle: "La Dolce Vita", chapterLabel: "Adventures", description: "Wine tour, a ton of pasta and pizza, and another lovely trip." },
  { folder: "Punta Cana", title: "Punta Cana", subtitle: "Caribbean Sun", chapterLabel: "Adventures", description: "Sun-drenched days and warm Caribbean nights." },
  { folder: "Ireland", title: "Ireland", subtitle: "The Emerald Isle", chapterLabel: "Adventures", description: "Rolling green hills, ancient castles, and hospitality that rivaled our own." },
  { folder: "Iceland", title: "Iceland", subtitle: "Fire & Ice", chapterLabel: "Adventures", description: "Probably the most beautiful place we have visited together as a family. Couldn't find the pictures of Blue Lagoon unfortunatley, definitely a highlight." },
  { folder: "St Martin", title: "St. Martin", subtitle: "Island Bliss", chapterLabel: "Adventures", description: "Two countries, one island, one unforgettable family vacation." },
  { folder: "France", title: "France", subtitle: "Joie de Vivre", chapterLabel: "Adventures", description: "Eifel Tower, lavender fields, the Louvre, and more" },
  { folder: "Barcelona", title: "Barcelona", subtitle: "Sun & Soul", chapterLabel: "Adventures", description: "Saw Messi and FCB play (dream come true)" },
  { folder: "South Africa", title: "South Africa", subtitle: "Wild at Heart", chapterLabel: "Adventures", description: "Probably one of if not my favorite trip together and the most unique. South African city and an eventful safari." },
  { folder: "Turks & Caicos", title: "Turks & Caicos", subtitle: "Crystal Waters", chapterLabel: "Adventures", description: "Really hitting my nerdiest era in Turks & Caicos, probably the best beach trip we've ever taken." },
  { folder: "Switzerland", title: "Switzerland", subtitle: "Alpine Dreams", chapterLabel: "Adventures", description: "Mountain peaks, chocolate, and train rides through storybook landscapes." },
  { folder: "Cabo Jetskis", title: "Cabo", subtitle: "Making Waves", chapterLabel: "Adventures", description: "Sun, speed, and salt spray. Racing across the Sea of Cortez." },
  { folder: "Hilton Head", title: "Hilton Head", subtitle: "Southern Charm", chapterLabel: "Adventures", description: "Sea breezes, kayaks, and pickleball!" },
  { folder: "Saudi Arabia", title: "Saudi Arabia", subtitle: "Back to Our Roots", chapterLabel: "Adventures", description: "A spiritual journey" },
  { folder: "Ameen", title: "Ameen", subtitle: "A Blessed Day", chapterLabel: "Milestones", description: "A sacred day of prayer, gratitude, and togetherness." },
  { folder: "Halloween 2019", title: "Halloween 2019", subtitle: "Trick or Treat", chapterLabel: "Milestones", description: "The costumes were creative, the candy was plentiful, and the laughter echoed down every street." },
  { folder: "Mama Birthday 2020", title: "Mama's Birthday", subtitle: "Heart of the Family", chapterLabel: "Milestones", description: "Celebrating the best mami in the world." },
  { folder: "2020 Ibrahim Birthday", title: "Ibrahim's Birthday", subtitle: "Another Year Older", chapterLabel: "Milestones", description: "Celebrating another trip around the sun." },
  { folder: "8th Grade Robotics State", title: "Robotics States", subtitle: "Dream Big", chapterLabel: "Milestones", description: "When hard work meets big dreams. Baba telling me that I need to calm down and smile more." },
  { folder: "Michigan 2020", title: "Michigan 2020", subtitle: "Lake Life", chapterLabel: "Milestones", description: "Big family trip" },
  { folder: "Fall Photo Shoot", title: "Fall Photo Shoot", subtitle: "Golden Hour", chapterLabel: "Milestones", description: "Autumn leaves, golden light, and beautiful family portraits." },
  { folder: "KitKat", title: "KitKat", subtitle: "Family Member", chapterLabel: "Milestones", description: "The demon from hell. Some moments he's an angel and then he pounces." },
];

export const featuredDescriptions: Record<string, string> = {
  "listening-in on the call": "Me in the stroller listening in as Baba takes yet another call.",
  "feeding-mama": "Sticking my hand in Mama's mouth to see if she'll bite it.",
  "hollywood-sign": "Our first big family trip out west. Explored legoland and had a blast!",
  "learning-to-walk": "Baba holding me up and teaching me to walk.",
  "mama-mummy": "Mama mummified at lego land!",
  "spaceship": "Baba and I flying a spaceship together from NASA",
  "watching-tv": "Lying down, schlumped, watching TV at home in North Dakota.",
  "drawing-with-baba": "Drawing with Babi, he seems to be taking it a lot more seriously than me",
  "lying-down-eating-my-shoes": "Lying down on a beach chair in Atlantis, eating my shoes.",
  "piggy-back-ride": "Hoisted up high on Baba's shoulders, seeing the world.",
  "riding-horse-with-mama": "Hold on tight! Riding a pony with Mama!",
  "something-surprising": "I don't know what happened here, but something very clealry surprising!",
  "tired-baba": "Tired Baba is done with me in this photo.",
  "yellow-car": "Driving my famous lellow car through jello powder in the living room.",
  "birthday": "Enjoying my 3rd birthday with my favorite Mami and Babi!",
  "driving-tractor-with-mama": "Me at the wheel driving the tractor, Mama scared for her life, as she always is when I drive.",
  "glass-floor": "Family on the glass floor!",
  "piggy-back-ride-adventure": "Round two. Me pointing in the direction I wanted to see.",
  "baba-me-spiderman-trio": "Meeting my favorite superhero, Spider-Man!",
  "baba-teaching-me-something": "Don't know if I was being scolded here or not, but I'm sure it was for a good reason.",
  "baba-weird-smile": "Something straight out of the Smile movie.",
  "christmas-hats": "Matching Christmas hats with my mami.",
  "curled-up-with-mama": "Curled up with Mama, on yet another trip.",
  "hooters-cabo": "Can't believe this happened. Pretty amazing photo.",
  "learning-from-baba": "Stalking everything Baba does clicking through his computer.",
  "fazolis-trip": "Family trip to Fazoli's, still going to this day! Can't belive I'm missing it from Singapore.",
  "mama-and-me-on-beach": "Sand between our toes, ocean in front of us, I wanted to go for a swim",
  "mama-and-me-school-play": "Mama and I at the school play, I was the best apple.",
  "classic-shazi-tantrum": "The legendary tantrum. Shazi starts the terrible 2's early. Mama trying to get her to stop crying with her pacifier.",
  "getting-ready-for-shazi": "The anticipation, the preparation, the excitement. Me and Mama at the hospital.",
  "helping-baba-build-table": "Me helping Baba build a table. Being a huge help as I always am.",
  "pregnant-mama": "Mama scowering menacingly at the camera.",
  "shazi-born-with-flowers": "Flowers for the newest Mohsin.",
  "shazi-born": "The day our family became complete.",
  "shazi-halloween": "Shazi as a ladybug! I think there was something sticky on my hands.",
  "baba-letting-me-drown": "Baba saving shazi from the water while I drown brutally.",
  "gettingreadyforphotoshoot": "Family all together getting ready for our photo shoot ",
  "happy-parent-shazi-trio": "Three smiles that say it all. Mama, Baba, and Shazi in their element - pure joy, no filter needed.",
  "mama-daughter-duo": "The bond between a mother and daughter, visible in a single frame. These two were inseparable from day one.",
  "mamainpakistanwithsleepingshazi": "Across the world, Shazi sleeps peacefully in Mama's arms. Home is not a place - it is a person.",
  "mamaweirdface": "Like father, like mother. The family tradition of making ridiculous faces carries on beautifully.",
  "sillyfamily": "No poses, no pretending. Just four people being completely, unapologetically themselves. The Mohsin family at our finest.",
  "familyatameentable": "Gathered together for a sacred celebration. Every face at this table carries the weight of gratitude and the lightness of joy.",
  "mamaandbaba": "The pillars of everything. In a room full of people, these two still only have eyes for the family they built.",
  "sayingmypiece": "Standing up, speaking from the heart. Some moments call for words, and this one deserved every syllable.",
  "tellingbabahownervousiam": "Even at our most anxious, Baba was always the calm in the storm. One look and the nerves started to fade.",
  "familyatourfavoritesoccerclub": "Standing where legends play. Our family at Barcelona's cathedral of football - a dream for any fan.",
  "mamaandbabaontheplayersbench": "Sitting where Messi sat. For one moment, Mama and Baba were the real MVPs.",
  "meandmamaatcampnou": "Two fans, one stadium, and a bond stronger than any rivalry.",
  "babaandshazi": "Two adventurers, one jet ski, and a whole ocean ahead. The best rides are the ones you take together.",
  "mamaandi": "Side by side on the water, salt in our hair. Just Mama and me - sometimes that is all you need.",
  "familyonsometractorthing": "We still do not know what this vehicle was, but we had the time of our lives on it.",
  "mamaandshazidrinkingcoconut": "Fresh coconut, warm sun, and the sweetest company. Island life looks good on these two.",
  "mamaandthestingray": "Mama's face says it all. Brave, terrified, and laughing all at once. The stingray was calm. Mama was not.",
  "shaziisveryscared": "The expression of pure, unfiltered fear. Whatever it was, Shazi wanted no part of it.",
  "babaandifiguringoutaudioguideatthelouvre": "Two generations versus one audio guide. The real masterpiece was watching us try to figure out the buttons.",
  "mamaandbabawithmonalisa": "Three smiles in one frame, though only one is famous.",
  "mamaandiandshaziinpalaceofversaille": "Walking the halls where kings and queens once lived. For one afternoon, the Mohsins were royalty.",
  "shaziclimbingongolfcart": "If there is a vehicle, Shazi will climb it. French countryside edition.",
  "familyatbluemosque": "Standing before centuries of history and beauty. The Blue Mosque took our breath away.",
  "mamasqueezingshazi’scheeks": "Those cheeks were made for squeezing, and Mama never missed an opportunity.",
  "medistrubingsleepingbaba": "Baba was trying to nap. I had other plans. The eternal struggle between a tired father and unlimited energy.",
  "babagivingsermoninglacier": "Only Baba could turn a glacier into a pulpit. The sermon was probably about being grateful.",
  "babaholdingmountainup": "Perspective tricks and Baba's sense of humor. He will tell you he actually held it.",
  "familyinwhoknowswhereiceland": "Lost in Iceland, found as a family. We had no idea where we were, but we knew who we were with.",
  "mamaandshaziontheriver": "Navigating Icelandic waters together. Mama and Shazi, always finding adventure wherever the current takes them.",
  "mamaandshaziwithrainbow": "You cannot plan a rainbow. But you can plan to be in Iceland with the people you love.",
  "familyeatingchocolate": "An Irish chocolate shop, four hungry Mohsins, and zero self-control.",
  "mamaandshaziinireland": "Two girls, one gorgeous backdrop, and the kind of bond that makes every photo feel like a painting.",
  "shazionbababack": "When little legs get tired, Baba's back is always open for business. Ireland by piggyback.",
  "beautifulitaliansunset": "Golden light over the Italian coast. Some moments do not need people in them - the beauty speaks for itself.",
  "familyinvenice": "Gondolas, bridges, and a family photo that belongs on a postcard.",
  "mamawithmoonmask": "When in Venice, you wear the mask. Mama embraced the tradition with style.",
  "babahappytoswim": "That smile when Baba hits the water. Pure happiness, no complications.",
  "faminatv": "Even in paradise, we found a screen. Some habits travel with you - but at least we were together.",
  "mamaandshaziwearingbabaclothesaftersuitcasegotlost": "When the airline loses your luggage, you improvise. Mama and Shazi in Baba's oversized clothes - fashion icons.",
  "familyinhotelroom": "Before heading out into the holy city, one last family photo. The excitement in every face tells the whole story.",
  "shaziandilaughingatsomething": "We do not remember what was funny. We never do. But the laughter, that, we will never forget.",
  "wholefamilyreadyforprayer": "Dressed and ready, hearts aligned. A family united in faith, standing together before something bigger than all of us.",
  "familyatwaterfall": "The sound of falling water, the spray on our faces, and a family photo with nature's most dramatic backdrop.",
  "mamaandbabatryingtogetgoodphoto": "The struggle is real. Twenty attempts, one good photo and the outtakes are honestly better.",
  "memamashaziandview": "Three of us, one incredible view, and a moment that made the whole trip worth it.",
  "parentsdiscussingontabletopmountain": "Even on top of Table Mountain, Mama and Baba found something to discuss. The view was breathtaking - the conversation, probably about dinner.",
  "shaziburyingbaba": "Baba agreed to be buried in sand. Shazi took the assignment very seriously.",
  "shaziswimmingtoparents": "Arms outstretched, kicking hard, swimming straight toward Mama and Baba. The destination was always them.",
};

export const featuredTitles: Record<string, string> = {
  "babasavingshaziwhileidrown": "Baba Saving Shazi While I Drown",
  "gettingreadyforphotoshoot": "Getting Ready For Photoshoot",
  "happy-parent-shazi-trio": "Happy Parent Shazi Trio",
  "mama-daughter-duo": "Mama Daughter Duo",
  "mamainpakistanwithsleepingshazi": "Mama in Pakistan with Sleeping Shazi",
  "mamaweirdface": "Mama Weird Face",
  "sillyfamily": "Silly Family",
  "familyatameentable": "Family At Ameen Table",
  "mamaandbaba": "Mama And Baba",
  "sayingmypiece": "Saying My Piece",
  "tellingbabahownervousiam": "Telling Baba How Nervous I Am",
  "familyatourfavoritesoccerclub": "Family At Our Favorite Soccer Club",
  "mamaandbabaontheplayersbench": "Mama And Baba On The Players Bench",
  "meandmamaatcampnou": "Me And Mama At Camp Nou",
  "babaandshazi": "Baba And Shazi",
  "mamaandi": "Mama And I",
  "familyonsometractorthing": "Family On Some Tractor Thing",
  "mamaandshazidrinkingcoconut": "Mama And Shazi Drinking Coconut",
  "mamaandthestingray": "Mama And The Stingray",
  "shaziisveryscared": "Shazi Is Very Scared",
  "babaandifiguringoutaudioguideatthelouvre": "Baba And I Figuring Out Audio Guide At The Louvre",
  "mamaandbabawithmonalisa": "Mama And Baba With Mona Lisa",
  "mamaandiandshaziinpalaceofversaille": "Mama And I And Shazi In Palace Of Versailles",
  "shaziclimbingongolfcart": "Shazi Climbing On Golf Cart",
  "familyatbluemosque": "Family At Blue Mosque",
  "mamasqueezingshazischeeks": "Mama Squeezing Shazi's Cheeks",
  "medistrubingsleepingbaba": "Me Disturbing Sleeping Baba",
  "babagivingsermoninglacier": "Baba Giving Sermon In Glacier",
  "babaholdingmountainup": "Baba Holding Mountain Up",
  "familyinwhoknowswhereiceland": "Family In Who Knows Where Iceland",
  "mamaandshaziontheriver": "Mama And Shazi On The River",
  "mamaandshaziwithrainbow": "Mama And Shazi With Rainbow",
  "familyeatingchocolate": "Family Eating Chocolate",
  "mamaandshaziinireland": "Mama And Shazi In Ireland",
  "shazionbababack": "Shazi On Baba Back",
  "beautifulitaliansunset": "Beautiful Italian Sunset",
  "familyinvenice": "Family In Venice",
  "mamawithmoonmask": "Mama With Moon Mask",
  "babahappytoswim": "Baba Happy To Swim",
  "faminatv": "Family At TV",
  "mamaandshaziwearingbabaclothesaftersuitcasegotlost": "Mama And Shazi Wearing Baba Clothes After Suitcase Got Lost",
  "familyinhotelroom": "Family In Hotel Room",
  "shaziandilaughingatsomething": "Shazi And I Laughing At Something",
  "wholefamilyreadyforprayer": "Whole Family Ready For Prayer",
  "familyatwaterfall": "Family At Waterfall",
  "mamaandbabatryingtogetgoodphoto": "Mama And Baba Trying To Get Good Photo",
  "memamashaziandview": "Me Mama Shazi And View",
  "parentsdiscussingontabletopmountain": "Parents Discussing On Table Top Mountain",
  "shaziburyingbaba": "Shazi Burying Baba",
  "shaziswimmingtoparents": "Shazi Swimming To Parents",
};
